Lesson2 task3
ivanori1/HelloJavaEndava pull request #8
Opened 2018-12-11 15:02 UTC by ivanori1

2018-12-11 15:07 UTC, endavamarko commented on Lesson0_HelloWorld/src/LotteryNumber.java
> +//
izbrisati stari kod pod komentarom

2018-12-11 15:08 UTC, endavamarko requested changes

2018-12-11 15:08 UTC, endavamarko commented on Lesson0_HelloWorld/src/LotteryNumber.java
> +             System.out.println("Unesi broj");
ubaciti da moze da se prekine petlja unosom nekog karaktera

2018-12-11 15:08 UTC, endavamarko commented on Lesson0_HelloWorld/src/LotteryNumber.java
> +        System.out.println("Broj je zamisljen! Probajte da ga pogodite.");
napisati koji karakter treba uneti da se prekine petlja

2018-12-11 16:04 UTC, ivanori1 commented
ne znam da li sam sada dobro uradio

2018-12-13 00:51 UTC, darkojovanovic approved these changes

2018-12-13 00:51 UTC, darkojovanovic commented on Lesson0_HelloWorld/src/LotteryNumber.java
> +                    } else if (vratiRezultat(zeljeniBroj, zamisljeniBroj) == 1) {
Nije potrebno istu metodu pozivati ponovo. Rezultat ove metode se cuva u promenljivoj 'rezultat'.

2018-12-13 01:10 UTC, darkojovanovic approved these changes

2018-12-13 08:37 UTC, merged